server:
  port: 8580
spring:
 application:
   name: employee-front-end
   
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}